name: Integração Contínua

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2
      
    - name: Configurar o Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Escolha a versão do Node.js que deseja usar
        
    - name: Instalar Dependências
      run: npm install
      
    - name: Executar Testes
      run: npm test